# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: golang
    # env:
      # BASE_URL: ${{secrets.BASE_URL}}


    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master
      with:
        dockerfile: Dockerfile
        context: .
   
    
    - name: Echo a variable
      run: echo "###### secrates ${{secrets.BASE_URL}}" 

    - name: Build Docker image
    
      run: docker build --build-arg "BASE_URL=${{ secrets.BASE_URL }}" -t golang_docker .

    
    - name: Run Docker container
      run: |
        docker run -p 5000:5000 -d golang_docker
    
    
